TRADUCCIONES = {
    "en": {
        "play": "PLAY",
        "options": "OPTIONS",
        "pause": "PAUSED",
        "continue": "CONTINUE",
        "exit": "EXIT",
        "resolution": "RESOLUTION",
        "display_mode": "DISPLAY MODE",
        "windowed": "WINDOWED",
        "fullscreen": "FULLSCREEN",
        "language": "LANGUAGE",
        "english": "ENGLISH",
        "spanish": "SPANISH",
        "portuguese": "PORTUGUESE",
        "russian": "RUSSIAN",
        "move_left": "MOVE LEFT",
        "move_right": "MOVE RIGHT",
        "jump": "JUMP",
        "crouch": "CROUCH",
        "press_key": "PRESS A KEY... ESC CANCELS",
        "back": "BACK",
        "apply": "APPLY",
        "retry": "RETRY",
        "level": "LEVEL",
        "window_title": "Procedural Platforms - Abstract Canvas",
    },
    "es": {
        "play": "JUGAR",
        "options": "OPCIONES",
        "pause": "PAUSA",
        "continue": "CONTINUAR",
        "exit": "SALIR",
        "resolution": "RESOLUCION",
        "display_mode": "MODO DE PANTALLA",
        "windowed": "VENTANA",
        "fullscreen": "PANTALLA COMPLETA",
        "language": "IDIOMA",
        "english": "INGLES",
        "spanish": "ESPANOL",
        "portuguese": "PORTUGUES",
        "russian": "RUSO",
        "move_left": "MOVER IZQUIERDA",
        "move_right": "MOVER DERECHA",
        "jump": "SALTAR",
        "crouch": "AGACHARSE",
        "press_key": "PULSA UNA TECLA... ESC CANCELA",
        "back": "VOLVER",
        "apply": "APLICAR",
        "retry": "REINTENTAR",
        "level": "NIVEL",
        "window_title": "Plataformas Procedurales - Lienzo Abstracto",
    },
    "pt": {
        "play": "JOGAR",
        "options": "OPÇÕES",
        "pause": "PAUSADO",
        "continue": "CONTINUAR",
        "exit": "SAIR",
        "resolution": "RESOLUÇÃO",
        "display_mode": "MODO DE EXIBIÇÃO",
        "windowed": "JANELA",
        "fullscreen": "TELA CHEIA",
        "language": "IDIOMA",
        "english": "INGLÊS",
        "spanish": "ESPANHOL",
        "portuguese": "PORTUGUÊS",
        "russian": "RUSSO",
        "move_left": "MOVER PARA ESQUERDA",
        "move_right": "MOVER PARA DIREITA",
        "jump": "PULAR",
        "crouch": "AGACHAR",
        "press_key": "PRESSIONE UMA TECLA... ESC CANCELA",
        "back": "VOLTAR",
        "apply": "APLICAR",
        "retry": "TENTAR NOVAMENTE",
        "level": "NÍVEL",
        "window_title": "Plataformas Procedurais - Tela Abstrata",
    },
    "ru": {
        "play": "ИГРАТЬ",
        "options": "ОПЦИИ",
        "pause": "ПАУЗА",
        "continue": "ПРОДОЛЖИТЬ",
        "exit": "ВЫХОД",
        "resolution": "РАЗРЕШЕНИЕ",
        "display_mode": "РЕЖИМ ЭКРАНА",
        "windowed": "ОКНО",
        "fullscreen": "ПОЛНЫЙ ЭКРАН",
        "language": "ЯЗЫК",
        "english": "АНГЛИЙСКИЙ",
        "spanish": "ИСПАНСКИЙ",
        "portuguese": "ПОРТУГАЛЬСКИЙ",
        "russian": "РУССКИЙ",
        "move_left": "ВЛЕВО",
        "move_right": "ВПРАВО",
        "jump": "ПРЫЖОК",
        "crouch": "ПРИСЕДАНИЕ",
        "press_key": "НАЖМИТЕ КЛАВИШУ... ESC ОТМЕНА",
        "back": "НАЗАД",
        "apply": "ПРИМЕНИТЬ",
        "retry": "ПОВТОРИТЬ",
        "level": "УРОВЕНЬ",
        "window_title": "Процедурные платформы - абстрактный холст",
    },
}


def texto(idioma, clave):
    return TRADUCCIONES.get(idioma, TRADUCCIONES["en"])[clave]


def alternar_idioma(idioma):
    secuencia = ["en", "es", "pt", "ru"]
    indice = secuencia.index(idioma) if idioma in secuencia else 0
    return secuencia[(indice + 1) % len(secuencia)]
