TRADUCCIONES = {
    "en": {
        "play": "PLAY",
        "options": "OPTIONS",
        "pause": "PAUSED",
        "continue": "CONTINUE",
        "exit": "EXIT",
        "resolution": "RESOLUTION",
        "display_mode": "DISPLAY MODE",
        "difficulty": "DIFFICULTY",
        "progressive_by_level": "PROGRESSIVE BY LEVEL",
        "windowed": "WINDOWED",
        "fullscreen": "FULLSCREEN",
        "language": "LANGUAGE",
        "music": "MUSIC",
        "effects": "EFFECTS",
        "ui_scale": "UI SCALE",
        "reset_defaults": "RESET DEFAULTS",
        "english": "ENGLISH",
        "spanish": "SPANISH",
        "portuguese": "PORTUGUESE",
        "russian": "RUSSIAN",
        "move_left": "MOVE LEFT",
        "move_right": "MOVE RIGHT",
        "jump": "JUMP",
        "crouch": "CROUCH",
        "press_key": "PRESS A KEY... ESC CANCELS",
        "back": "BACK",
        "apply": "APPLY",
        "retry": "RETRY",
        "epilepsy_warning_title": "EPILEPSY WARNING",
        "epilepsy_warning_line_1": "This game contains flashing lights and visual effects",
        "epilepsy_warning_line_2": "that may trigger seizures in some people.",
        "epilepsy_warning_continue": "PRESS ANY KEY OR CLICK TO CONTINUE",
        "level_10_flashback": "It's strange, isn't it?",
        "level_22_flashback": "It gets harder, right?",
        "level": "LEVEL",
        "window_title": "Procedural Platforms - Abstract Canvas",
    },
    "es": {
        "play": "JUGAR",
        "options": "OPCIONES",
        "pause": "PAUSA",
        "continue": "CONTINUAR",
        "exit": "SALIR",
        "resolution": "RESOLUCION",
        "display_mode": "MODO DE PANTALLA",
        "difficulty": "DIFICULTAD",
        "progressive_by_level": "PROGRESIVA POR NIVEL",
        "windowed": "VENTANA",
        "fullscreen": "PANTALLA COMPLETA",
        "language": "IDIOMA",
        "music": "MUSICA",
        "effects": "EFECTOS",
        "ui_scale": "ESCALA DE INTERFAZ",
        "reset_defaults": "RESTAURAR PREDETERMINADO",
        "english": "INGLES",
        "spanish": "ESPANOL",
        "portuguese": "PORTUGUES",
        "russian": "RUSO",
        "move_left": "MOVER IZQUIERDA",
        "move_right": "MOVER DERECHA",
        "jump": "SALTAR",
        "crouch": "AGACHARSE",
        "press_key": "PULSA UNA TECLA... ESC CANCELA",
        "back": "VOLVER",
        "apply": "APLICAR",
        "retry": "REINTENTAR",
        "epilepsy_warning_title": "ADVERTENCIA DE EPILEPSIA",
        "epilepsy_warning_line_1": "Este juego contiene luces intermitentes y efectos visuales",
        "epilepsy_warning_line_2": "que pueden provocar convulsiones en algunas personas.",
        "epilepsy_warning_continue": "PULSA UNA TECLA O HAZ CLIC PARA CONTINUAR",
        "level_10_flashback": "Es raro, no?",
        "level_22_flashback": "Se vuelve difícil, verdad?",
        "level": "NIVEL",
        "window_title": "Plataformas Procedurales - Lienzo Abstracto",
    },
    "pt": {
        "play": "JOGAR",
        "options": "OPÇÕES",
        "pause": "PAUSADO",
        "continue": "CONTINUAR",
        "exit": "SAIR",
        "resolution": "RESOLUÇÃO",
        "display_mode": "MODO DE EXIBIÇÃO",
        "difficulty": "DIFICULDADE",
        "progressive_by_level": "PROGRESSIVA POR NÍVEL",
        "windowed": "JANELA",
        "fullscreen": "TELA CHEIA",
        "language": "IDIOMA",
        "music": "MÚSICA",
        "effects": "EFEITOS",
        "ui_scale": "ESCALA DA INTERFACE",
        "reset_defaults": "RESTAURAR PADRÃO",
        "english": "INGLÊS",
        "spanish": "ESPANHOL",
        "portuguese": "PORTUGUÊS",
        "russian": "RUSSO",
        "move_left": "MOVER PARA ESQUERDA",
        "move_right": "MOVER PARA DIREITA",
        "jump": "PULAR",
        "crouch": "AGACHAR",
        "press_key": "PRESSIONE UMA TECLA... ESC CANCELA",
        "back": "VOLTAR",
        "apply": "APLICAR",
        "retry": "TENTAR NOVAMENTE",
        "epilepsy_warning_title": "AVISO DE EPILEPSIA",
        "epilepsy_warning_line_1": "Este jogo contém luzes intermitentes e efeitos visuais",
        "epilepsy_warning_line_2": "que podem causar convulsões em algumas pessoas.",
        "epilepsy_warning_continue": "PRESSIONE UMA TECLA OU CLIQUE PARA CONTINUAR",
        "level_10_flashback": "E estranho, nao e?",
        "level_22_flashback": "Fica mais difícil, né?",
        "level": "NÍVEL",
        "window_title": "Plataformas Procedurais - Tela Abstrata",
    },
    "ru": {
        "play": "ИГРАТЬ",
        "options": "ОПЦИИ",
        "pause": "ПАУЗА",
        "continue": "ПРОДОЛЖИТЬ",
        "exit": "ВЫХОД",
        "resolution": "РАЗРЕШЕНИЕ",
        "display_mode": "РЕЖИМ ЭКРАНА",
        "difficulty": "СЛОЖНОСТЬ",
        "progressive_by_level": "ПОСТЕПЕННАЯ ПО УРОВНЮ",
        "windowed": "ОКНО",
        "fullscreen": "ПОЛНЫЙ ЭКРАН",
        "language": "ЯЗЫК",
        "music": "МУЗЫКА",
        "effects": "ЭФФЕКТЫ",
        "ui_scale": "МАСШТАБ ИНТЕРФЕЙСА",
        "reset_defaults": "СБРОСИТЬ ПО УМОЛЧАНИЮ",
        "english": "АНГЛИЙСКИЙ",
        "spanish": "ИСПАНСКИЙ",
        "portuguese": "ПОРТУГАЛЬСКИЙ",
        "russian": "РУССКИЙ",
        "move_left": "ВЛЕВО",
        "move_right": "ВПРАВО",
        "jump": "ПРЫЖОК",
        "crouch": "ПРИСЕДАНИЕ",
        "press_key": "НАЖМИТЕ КЛАВИШУ... ESC ОТМЕНА",
        "back": "НАЗАД",
        "apply": "ПРИМЕНИТЬ",
        "retry": "ПОВТОРИТЬ",
        "epilepsy_warning_title": "ПРЕДУПРЕЖДЕНИЕ ОБ ЭПИЛЕПСИИ",
        "epilepsy_warning_line_1": "В этой игре есть мигающие огни и визуальные эффекты,",
        "epilepsy_warning_line_2": "которые могут вызвать приступы у некоторых людей.",
        "epilepsy_warning_continue": "НАЖМИТЕ ЛЮБУЮ КЛАВИШУ ИЛИ КЛИКНИТЕ ДЛЯ ПРОДОЛЖЕНИЯ",
        "level_10_flashback": "Странно, не правда ли?",
        "level_22_flashback": "Становится сложнее, правда?",
        "level": "УРОВЕНЬ",
        "window_title": "Процедурные платформы - абстрактный холст",
    },
}


def texto(idioma, clave):
    return TRADUCCIONES.get(idioma, TRADUCCIONES["en"])[clave]


def alternar_idioma(idioma):
    secuencia = ["en", "es", "pt", "ru"]
    indice = secuencia.index(idioma) if idioma in secuencia else 0
    return secuencia[(indice + 1) % len(secuencia)]
